[debug] [2025-09-16T03:41:34.468Z] ----------------------------------------------------------------------
[debug] [2025-09-16T03:41:34.471Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\axel5\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js login
[debug] [2025-09-16T03:41:34.471Z] CLI Version:   14.15.2
[debug] [2025-09-16T03:41:34.472Z] Platform:      win32
[debug] [2025-09-16T03:41:34.472Z] Node Version:  v20.17.0
[debug] [2025-09-16T03:41:34.472Z] Time:          Mon Sep 15 2025 21:41:34 GMT-0600 (hora estÃ¡ndar central)
[debug] [2025-09-16T03:41:34.472Z] ----------------------------------------------------------------------
[debug] 
[debug] [2025-09-16T03:41:34.474Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[info] Already logged in as axel5alvarez536@gmail.com
[debug] [2025-09-16T03:41:37.792Z] <<< [apiv2][status] GET https://firebase-public.firebaseio.com/cli.json 200
[debug] [2025-09-16T03:41:37.793Z] <<< [apiv2][body] GET https://firebase-public.firebaseio.com/cli.json {"cloudBuildErrorAfter":1594252800000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390400000,"node8RuntimeDisabledAfter":1615809600000,"node8WarnAfter":1600128000000}
[debug] [2025-09-16T03:41:39.740Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\axel5\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:273:49)
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7)
[error] 
[error] Error: An unexpected error has occurred.
